version: "3.7"

services:
  micro-sample-nginx-proxy:
    container_name: "micro-sample-nginx-proxy"
    image: "nginx"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "8080:80"
    links:
      - "micro-sample-service1"
      - "micro-sample-service2"

  micro-sample-service1:
    container_name: "micro-sample-service1"
    build: "./service1"

  micro-sample-service2:
    container_name: "micro-sample-service2"
    build: "./service2"
